python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4 --num_epochs 50 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha --num_epochs 50 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_64 --num_epochs 50 --hidden_layers 64 64 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_64l3 --num_epochs 50 --hidden_layers 64 64 64 --batch_size 1024 --learning_rate 0.005 --decay_steps 10 --decay_rate 0.7
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_32l3 --num_epochs 50 --hidden_layers 32 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_64l2 --num_epochs 100 --hidden_layers 64 64 --batch_size 1024 --learning_rate 0.01 --decay_steps 10 --decay_rate 0.7
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_64l2_drop_wd --num_epochs 100 --hidden_layers 64 64 --batch_size 1024 --learning_rate 0.01 --decay_steps 10 --decay_rate 0.7 --dropout_rate 0.1 --weight_decay 0
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_32l3_drop_wd --num_epochs 50 --hidden_layers 32 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7 --dropout_rate 0.1 --weight_decay 0
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_32l3_drop_wd --num_epochs 50 --hidden_layers 32 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7 --dropout_rate 0.001 --weight_decay 0
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_64l2_drop_wd --num_epochs 100 --hidden_layers 64 64 --batch_size 1024 --learning_rate 0.001 --decay_steps 50 --decay_rate 0.8 --dropout_rate 0.0001 --weight_decay 0
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_32l2 --num_epochs 100 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.001 --decay_steps 50 --decay_rate 0.8 --dropout_rate 0.0001 --weight_decay 0
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m4_cha_32l2 --num_epochs 100 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.001 --decay_steps 10 --decay_rate 0.8 --dropout_rate 0.001 --weight_decay 0
python executor.py --module m4 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name test_unnormalized --num_epochs 20 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.001 --decay_steps 10 --decay_rate 0.8 --dropout_rate 0.001 --weight_decay 0


python executor.py --module m3 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m3_resp --num_epochs 50 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7
python executor.py --module m3 --data_file "all_data_lake_modeling_process_based.csv" --cuda_device 1 --wandb_run_name m3_wo_resp --num_epochs 50 --hidden_layers 32 32 --batch_size 1024 --learning_rate 0.01 --decay_steps 5 --decay_rate 0.7
